version: "3"

services:
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test

  node:
    container_name: node
    build: 
      context: node
    ports:
      - 8000:3000
    entrypoint: ./start_server.sh
    depends_on:
      - db
  
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/nginx_conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - node